### ISSUE TITLE
Unsupported major.minor version 52.0 on Mint 17.3 KDE AMD64

### ISSUE THREAD

**Issue by QuAzI** [Wolfsblvt/BlossomsPokemonGoManager#121]
When I try to run 

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: me/corriekay/pokegoutil/BlossomsPoGoManager : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

```
> java -version
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```

**Comment by Wolfsblvt** [comment]
You need Java 8 to run this app, like specified in the installation section.
Seems like you only have Java 7 there.

**Comment by QuAzI** [comment]
In most linux distributes Java8 still not in repository of stable software :(
Is any specific for Java8 features required or requirements can be downgraded?

**Comment by QuAzI** [comment]
As alternative variant place this in FAQ

```
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer
```

Source: http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html

**Comment by Wolfsblvt** [comment]
Yes, we use lambda expressions quite much. And I thought Java 8 is already standard on like every system? o.O
Strange thing. I will add it to the faq, good indea.

**Comment by Wolfsblvt** [comment]
Added to the FAQ. Thanks.

**Comment by Lacero** [comment]
> And I thought Java 8 is already standard on like every system? 

I'm forced to use Java 6 and 7 in corporate world. A lot of red tape to get to Java 8 but it is coming this year.

My search for "->" showed 21 lambda expressions. Is entirely possible to replace them with the longer loops and inner classes. Still, requiring Java 8 is a reasonable request considering the security beating Java 7 took. I wouldn't mind forking to "downgrade" to Java 6-7 if there is enough demand for it.

**Comment by Wolfsblvt** [comment]
I guess most persons using this software are private people and should not have any problems using Java 8.
I would say it isn't worth the work to downgrade, and I don't want to miss the language features Java offers just for a few edge cases like <1% of people or something :D

**Comment by weblue** [comment]
@Lacero that's probably fair and would increase compatibility. I think if you ended up forking it for Java 7 we could add it as a compatibility release branch, but I doubt anyone would really want to do it otherwise.
