### ISSUE TITLE
The manager doesn't open up (Maybe related to token not escaped for JSON)

### ISSUE THREAD

**Issue by Soukatsoui** [Wolfsblvt/BlossomsPokemonGoManager#138]
Hello.

All is said in the title, the manager doesn't show up after I parse my Google token. But Javaw appears in the current process.

Can anyone help me with it, please?

**Comment by juemrami** [comment]
@Wolfsblvt having same problem tried what you recommended its giving me log-in fail.

**Comment by Wolfsblvt** [comment]
Okay, we will release a new pre-release soon. Guess you have to wait for that, that should fix most of that problems.

**Comment by reesh19** [comment]
I have two accounts for PoGo. Everything worked perfectly with my _probing_ account, but after logging out and trying to log in with my second account I got the same issue as described. I tried deleting everything and unzipping again and selecting "Yes" and "No" when it asks to save the google token, as well as using the script above, but no luck. Just thought I would share the extra information. I was able to log in once.

**Comment by Tinytox** [comment]
I am also having this issue. My Google auth has a backslash ( \ ) in it, I figured perhaps this is an escape character related issue? I have no idea if they typically have symbols that could be considered escape characters.

**Comment by Wolfsblvt** [comment]
@Tinytox Oh god, you may have a point there!
That could be the reason why it sometimes works, sometimes not. You get a new token every few ours.

Will make a fix for that. We'll see if that's enough.

**Comment by Soukatsoui** [comment]
Hey again,

First, thanks for your help :)

I'm back to update you about my situation. Well, in my situation, I get a new token everytime the page that gives me one loads, and, sometimes it lets me log in, sometimes it doesn't. Didn't really pay attention about backslashes when it worked or didn't work, but yeah, he may have a point ^^

Thanks again for your reactivity :)

**Comment by Wolfsblvt** [comment]
Okay guys, a new version is released!
It may fix this bug, but I need a clear response if it does.
Can someone of you test it and give a short answer?

The new release can be found here: [v0.1.2-alpha.1](https://github.com/Blossomforth/BlossomsPokemonGoManager/releases/tag/v0.1.2-alpha.1)

**Comment by AshaneF** [comment]
I was having the issue as well.

The above alpha version fixed the issue for me. I can now login.

However, it's spitting out a few errors now.

"[08/09 22:26:07]: Unable to login!
[08/09 22:26:07]: com.pokegoapi.exceptions.RemoteServerException: Contents of buffer are null
[08/09 22:26:07]:   at com.pokegoapi.util.FutureWrapper.toBlocking(FutureWrapper.java:119)
[08/09 22:26:07]:   at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:154)
[08/09 22:26:07]:   at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:108)
[08/09 22:26:07]:   at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
[08/09 22:26:07]:   at com.pokegoapi.api.inventory.Inventories.<init>(Inventories.java:74)
[08/09 22:26:07]:   at com.pokegoapi.api.PokemonGo.getInventories(PokemonGo.java:135)
[08/09 22:26:07]:   at com.pokegoapi.api.player.PlayerProfile.getStats(PlayerProfile.java:304)
[08/09 22:26:07]:   at me.corriekay.pokegoutil.windows.PokemonGoMainWindow.<init>(PokemonGoMainWindow.java:43)
[08/09 22:26:07]:   at me.corriekay.pokegoutil.controllers.AccountController.logOn(AccountController.java:194)
[08/09 22:26:07]:   at me.corriekay.pokegoutil.BlossomsPoGoManager.main(BlossomsPoGoManager.java:19)
[08/09 22:26:07]: Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
[08/09 22:26:07]:   at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
[08/09 22:26:07]:   at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:292)
[08/09 22:26:07]:   at java.lang.Thread.run(Unknown Source)
"

Love the program btw :) Its priceless!

**Comment by Wolfsblvt** [comment]
With which particular program? What do you mean?

**Comment by AshaneF** [comment]
Sorry, the alpha version you released spit out that error at first login and second login. Erasing the google auth key and generating a new one seems to have fixed the issue above.

(Program being PokemonGo Manager ;D)

**Comment by Wolfsblvt** [comment]
Ah yeah. If there are issues, always try to delete the `config.json` first. That helps often :D

**Comment by patrissimo** [comment]
I had a forward-slash ("/") containing token which wasn't working in v0.1.1b ("Exception in thread "main" [08/09 23:53:48]: com.pokegoapi.exceptions.LoginFailedException: invalid_request"); and the alpha release, with the same token, worked. So, looking good! I can also see the escaping in config.json.

**Comment by Tinytox** [comment]
Yep, this did resolve it and I am able to log in now!
Thanks for the quick patch!
