### ISSUE TITLE
Sorting "to Evolve" column raises exception

### ISSUE THREAD

**Issue by k4n30** [Wolfsblvt/BlossomsPokemonGoManager#153]
When trying to sort "to evolve" column

[08/10 11:49:10]: Exception in thread "AWT-EventQueue-0" [08/10 11:49:10]: java.lang.NullPointerException
[08/10 11:49:10]:   at me.corriekay.pokegoutil.windows.PokemonTab$PokemonTable.lambda$constructNewTableModel$3(PokemonTab.java:624)
[08/10 11:49:10]:   at javax.swing.DefaultRowSorter.compare(DefaultRowSorter.java:968)
[08/10 11:49:10]:   at javax.swing.DefaultRowSorter.access$100(DefaultRowSorter.java:112)
[08/10 11:49:10]:   at javax.swing.DefaultRowSorter$Row.compareTo(DefaultRowSorter.java:1376)
[08/10 11:49:10]:   at javax.swing.DefaultRowSorter$Row.compareTo(DefaultRowSorter.java:1366)
[08/10 11:49:10]:   at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:320)
[08/10 11:49:10]:   at java.util.ComparableTimSort.sort(ComparableTimSort.java:202)
[08/10 11:49:10]:   at java.util.Arrays.sort(Arrays.java:1246)
[08/10 11:49:10]:   at javax.swing.DefaultRowSorter.sortExistingData(DefaultRowSorter.java:553)
[08/10 11:49:10]:   at javax.swing.DefaultRowSorter.setSortKeys(DefaultRowSorter.java:321)
[08/10 11:49:10]:   at javax.swing.DefaultRowSorter.toggleSortOrder(DefaultRowSorter.java:480)
[08/10 11:49:10]:   at javax.swing.plaf.basic.BasicTableHeaderUI$MouseInputHandler.mouseClicked(BasicTableHeaderUI.java:112)
[08/10 11:49:10]:   at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
[08/10 11:49:10]:   at java.awt.Component.processMouseEvent(Component.java:6536)
[08/10 11:49:10]:   at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
[08/10 11:49:10]:   at java.awt.Component.processEvent(Component.java:6298)
[08/10 11:49:10]:   at java.awt.Container.processEvent(Container.java:2236)
[08/10 11:49:10]:   at java.awt.Component.dispatchEventImpl(Component.java:4889)
[08/10 11:49:10]:   at java.awt.Container.dispatchEventImpl(Container.java:2294)
[08/10 11:49:10]:   at java.awt.Component.dispatchEvent(Component.java:4711)
[08/10 11:49:10]:   at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
[08/10 11:49:10]:   at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
[08/10 11:49:10]:   at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
[08/10 11:49:10]:   at java.awt.Container.dispatchEventImpl(Container.java:2280)
[08/10 11:49:10]:   at java.awt.Window.dispatchEventImpl(Window.java:2746)
[08/10 11:49:10]:   at java.awt.Component.dispatchEvent(Component.java:4711)
[08/10 11:49:10]:   at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
[08/10 11:49:10]:   at java.awt.EventQueue.access$500(EventQueue.java:97)
[08/10 11:49:10]:   at java.awt.EventQueue$3.run(EventQueue.java:709)
[08/10 11:49:10]:   at java.awt.EventQueue$3.run(EventQueue.java:703)
[08/10 11:49:10]:   at java.security.AccessController.doPrivileged(Native Method)
[08/10 11:49:10]:   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
[08/10 11:49:10]:   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[08/10 11:49:10]:   at java.awt.EventQueue$4.run(EventQueue.java:731)
[08/10 11:49:10]:   at java.awt.EventQueue$4.run(EventQueue.java:729)
[08/10 11:49:10]:   at java.security.AccessController.doPrivileged(Native Method)
[08/10 11:49:10]:   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
[08/10 11:49:10]:   at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
[08/10 11:49:10]:   at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
[08/10 11:49:10]:   at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
[08/10 11:49:10]:   at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
[08/10 11:49:10]:   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[08/10 11:49:10]:   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
[08/10 11:49:10]:   at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by weblue** [comment]
the comparator is set to sort by numbers but has dashes in that line

**Comment by weblue** [comment]
There's actually a todo to fix that

**Comment by Wolfsblvt** [comment]
The ug is already fixed :D
See the linked merge.
