### ISSUE TITLE
null pointer error

### ISSUE THREAD

**Issue by jk1z** [Wolfsblvt/BlossomsPokemonGoManager#249]
[08/15 13:55:15]: Could not fetch config item 'login.PTCUsername'! Fallback to default: null
[08/15 13:55:16]: Could not fetch config item 'login.PTCPassword'! Fallback to default: null
[08/15 13:55:20]: Could not fetch config item 'login.GoogleAuthToken'! Fallback to default: null
[08/15 13:55:34]: D/GoogleUserCredentialProvider: 3600
[08/15 13:55:34]: D/GoogleUserCredentialProvider: Got token: `****************************
[08/15 13:55:34]: Could not fetch config item 'login.SaveAuth'! Fallback to default: false
[08/15 13:55:37]: D/RequestHandler: Authenticated with static token
[08/15 13:55:38]: Successfully logged in. Welcome, *******.
[08/15 13:55:39]: Exception in thread "main" [08/15 13:55:39]: java.lang.NullPointerException
[08/15 13:55:39]:   at me.corriekay.pokegoutil.windows.PokemonGoMainWindow.<init>(PokemonGoMainWindow.java:43)
[08/15 13:55:39]:   at me.corriekay.pokegoutil.controllers.AccountController.logOn(AccountController.java:194)
[08/15 13:55:39]:   at me.corriekay.pokegoutil.BlossomsPoGoManager.main(BlossomsPoGoManager.java:19)

I have masked my username and token with *.
Should be easy to fix in the source code :)

**Comment by Wolfsblvt** [comment]
> Should be easy to fix in the source code :)

Seems so :P
We will do.

**Comment by Wolfsblvt** [comment]
Wait, the bug isn't what it seems. Doesn't have anything to do with saved login data returned as null.

Which version do you use? The latest Alpha?
Need to check to compare the line numbers where the exception is.
I guess it's more related to general login problems and/or account ban. Can you use the app after that error?
Can you play with that account on your smartphone?

**Comment by Wolfsblvt** [comment]
I will close here, cause there was no further feedback.
Will re-open if there will be a new response.
