### ISSUE TITLE
RemoteServerException

### ISSUE THREAD

**Issue by ssachtleben** [Wolfsblvt/BlossomsPokemonGoManager#250]
Hey,

I run into this issue (auth by google):

[08/15 09:36:00]: D/RequestHandler: Authenticated with static token
[08/15 09:36:01]: Exception in thread "main" [08/15 09:36:01]: com.pokegoapi.exceptions.RemoteServerException: Contents of buffer are null
[08/15 09:36:01]:   at com.pokegoapi.util.FutureWrapper.toBlocking(FutureWrapper.java:119)
[08/15 09:36:01]:   at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:154)
[08/15 09:36:01]:   at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:108)
[08/15 09:36:01]:   at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
[08/15 09:36:01]:   at com.pokegoapi.api.inventory.Inventories.<init>(Inventories.java:74)
[08/15 09:36:01]:   at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:82)
[08/15 09:36:01]:   at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:100)
[08/15 09:36:01]:   at me.corriekay.pokegoutil.BlossomsPoGoManager.logOn(BlossomsPoGoManager.java:213)
[08/15 09:36:01]:   at me.corriekay.pokegoutil.BlossomsPoGoManager.main(BlossomsPoGoManager.java:50)
[08/15 09:36:01]: Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
[08/15 09:36:01]:   at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
[08/15 09:36:01]:   at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:292)
[08/15 09:36:01]:   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[08/15 09:36:01]:   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[08/15 09:36:01]:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[08/15 09:36:01]:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[08/15 09:36:01]:   at java.lang.Thread.run(Thread.java:745)

Account works great on phone, anything I can assist with?

**Comment by xephael** [comment]
I believe this basically just means the API didn't respond in time. Meaning your connection is slow or the pokemon go servers are having issues. Basically just try loading it again.

**Comment by ssachtleben** [comment]
Timeout in 1s? ;)

Problem still exists.

**Comment by xephael** [comment]
I'm not sure what you mean

**Comment by ssachtleben** [comment]
Well it says 09:36:00 authenticated and 09:36:01 exception occur, so there is only 1s between.

But it seems its related to PokeGO-API library which is used here. Sadly I cant see what happens in the line of code with the exception since the Class is already updated in the master branch of that lib.

**Comment by Wolfsblvt** [comment]
"Contents of buffer are null" is an exception thrown by PokeGo-API, which seem to hit quite a few users here.
I have investigated already, but there is no real chance to find the issue, I would say. Don't know what we could do here.

As long as we don't know the reason what's causing this, we can't do more than just try to... _handle_ that exception, for example with an application restart.

Some users also get that when they transfer a lot of Pokémon at once for some Pokémon, others are successful.
I always felt like it is related to the API limiting its answers to the clients. For overall calls, but more for time inbetween some calls of the same client.

We could prove that if we test and add two seconds delay between everything that calls the api. But I don't have the time to do so.

**Comment by ssachtleben** [comment]
Ok I can use the app now. It seems like its not working if you have no Pokeballs at all. At that time I only had Ultraballs, now I have normal Pokeballs and it works. Its just a guess but it breaks on update Inventory so its most likely that.

**Comment by Wolfsblvt** [comment]
Thank you for your feedback.

**Comment by ISeeTanamon** [comment]
Hey @Wolfsblvt 

Just wanted to drop the exception I see below. When renaming 4 pokemon at a time or less, we're okay, we refresh. If we name 5, we always get the exception. Its possible we're going too fast. I know this issue is closed, but I was wondering if we're better off adding a greater buffer between transferring/evolving/renaming. I see it a lot when I do a mass batch. 

[08/17 04:25:22]: com.pokegoapi.exceptions.RemoteServerException: Contents of buffer are null
[08/17 04:25:22]:   at com.pokegoapi.util.FutureWrapper.toBlocking(FutureWrapper.java:119)
[08/17 04:25:22]:   at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:154)
[08/17 04:25:22]:   at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:108)
[08/17 04:25:22]:   at me.corriekay.pokegoutil.windows.PokemonTab.renameSelected(PokemonTab.java:233)
[08/17 04:25:22]:   at me.corriekay.pokegoutil.windows.PokemonTab.access$1000(PokemonTab.java:65)
[08/17 04:25:22]:   at me.corriekay.pokegoutil.windows.PokemonTab$2.doInBackground(PokemonTab.java:96)
[08/17 04:25:22]:   at me.corriekay.pokegoutil.windows.PokemonTab$2.doInBackground(PokemonTab.java:94)
[08/17 04:25:22]:   at javax.swing.SwingWorker$1.call(Unknown Source)
[08/17 04:25:22]:   at java.util.concurrent.FutureTask.run(Unknown Source)
[08/17 04:25:22]:   at javax.swing.SwingWorker.run(Unknown Source)
[08/17 04:25:22]:   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[08/17 04:25:22]:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[08/17 04:25:22]:   at java.lang.Thread.run(Unknown Source)
[08/17 04:25:22]: Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
[08/17 04:25:22]:   at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
[08/17 04:25:22]:   at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:292)
