### ISSUE TITLE
crashing after saving login info

### ISSUE THREAD

**Issue by weblue** [Wolfsblvt/BlossomsPokemonGoManager#28]
Exception in thread "main" org.json.JSONException: JSONObject["login"] not found.
    at org.json.JSONObject.get(JSONObject.java:471)
    at org.json.JSONObject.getJSONObject(JSONObject.java:636)
    at me.corriekay.pokegoutil.BlossomsPoGoManager.logOn(BlossomsPoGoManager.java:52)
    at me.corriekay.pokegoutil.BlossomsPoGoManager.main(BlossomsPoGoManager.java:43)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by weblue** [comment]
@Ljaysoft

**Comment by Ljaysoft** [comment]
I'm getting server errors as well, everything was working fine half an hour ago.. investigating

**Comment by ghost** [comment]
This isnt an issue with the server, this is an issue with the JSONConfig. Originally it was an object with the login details, but now that we're going to need options/configuration etc, i moved all of the login data into an object named login. If you're getting this, im betting all you need to do is delete config.json, and reboot the app.

**Comment by weblue** [comment]
I tried that to solve it; the json keeps going back. I think the json isn't being written properly on saving login info and it's being overwritten by something else after the fact.

**Comment by wullxz** [comment]
Something is still saving the settings with the old format (without the login object)...
- I pulled the current version, deleted the config json and was able to start the application.  
- I closed and restarted it, it failed, because there was no login object in the config anymore
- I enclosed auth information in a login object and it worked again but saved the old format after closing the application again.

**Comment by wullxz** [comment]
I solved it... PR incoming in a min.
