### ISSUE TITLE
Manager sometimes wont start 

### ISSUE THREAD

**Issue by Nikecow** [Wolfsblvt/BlossomsPokemonGoManager#402]
Hello,

I have to start the manager multiple times before it starts sometimes. Here is the log:

`
[22:59:48]: com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
[22:59:48]:     at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:46)
[22:59:48]:     at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
[22:59:48]:     at com.pokegoapi.api.PokemonGo.fireRequestBlockTwo(PokemonGo.java:230)
[22:59:48]:     at com.pokegoapi.api.PokemonGo.initialize(PokemonGo.java:170)
[22:59:48]:     at com.pokegoapi.api.PokemonGo.login(PokemonGo.java:164)
[22:59:48]:     at me.corriekay.pokegoutil.data.managers.AccountController.logOn(AccountController.java:218)
[22:59:48]:     at me.corriekay.pokegoutil.data.managers.AccountController.logOff(AccountController.java:342)
[22:59:48]:     at me.corriekay.pokegoutil.windows.MenuBar.logout(MenuBar.java:139)
[22:59:48]:     at me.corriekay.pokegoutil.windows.MenuBar.lambda$new$52(MenuBar.java:44)
[22:59:48]:     at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
[22:59:48]:     at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
[22:59:48]:     at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
[22:59:49]:     at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
[22:59:49]:     at javax.swing.AbstractButton.doClick(Unknown Source)
[22:59:49]:     at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
[22:59:49]:     at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
[22:59:49]:     at java.awt.Component.processMouseEvent(Unknown Source)
[22:59:49]:     at javax.swing.JComponent.processMouseEvent(Unknown Source)
[22:59:49]:     at java.awt.Component.processEvent(Unknown Source)
[22:59:49]:     at java.awt.Container.processEvent(Unknown Source)
[22:59:49]:     at java.awt.Component.dispatchEventImpl(Unknown Source)
[22:59:49]:     at java.awt.Container.dispatchEventImpl(Unknown Source)
[22:59:49]:     at java.awt.Component.dispatchEvent(Unknown Source)
[22:59:49]:     at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[22:59:49]:     at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[22:59:49]:     at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[22:59:49]:     at java.awt.Container.dispatchEventImpl(Unknown Source)
[22:59:49]:     at java.awt.Window.dispatchEventImpl(Unknown Source)
[22:59:49]:     at java.awt.Component.dispatchEvent(Unknown Source)
[22:59:49]:     at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[22:59:49]:     at java.awt.EventQueue.access$500(Unknown Source)
[22:59:49]:     at java.awt.EventQueue$3.run(Unknown Source)
[22:59:49]:     at java.awt.EventQueue$3.run(Unknown Source)
[22:59:49]:     at java.security.AccessController.doPrivileged(Native Method)
[22:59:49]:     at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[22:59:49]:     at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[22:59:49]:     at java.awt.EventQueue$4.run(Unknown Source)
[22:59:49]:     at java.awt.EventQueue$4.run(Unknown Source)
[22:59:49]:     at java.security.AccessController.doPrivileged(Native Method)
[22:59:49]:     at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[22:59:49]:     at java.awt.EventQueue.dispatchEvent(Unknown Source)
[22:59:49]:     at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[22:59:49]:     at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[22:59:49]:     at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[22:59:49]:     at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[22:59:49]:     at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[22:59:49]:     at java.awt.EventDispatchThread.run(Unknown Source)
[22:59:49]: Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
[22:59:49]:     at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
[22:59:49]:     at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
[22:59:49]:     at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
[22:59:49]:     at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:38)
[22:59:49]:     ... 46 more
[22:59:49]: Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
[22:59:49]:     at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
[22:59:49]:     at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
[22:59:49]:     at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
[22:59:49]:     at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
[22:59:49]:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
[22:59:49]:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[22:59:49]:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
[22:59:49]:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[22:59:49]:     at rx.Observable.subscribe(Observable.java:9957)
[22:59:49]:     at rx.Observable.subscribe(Observable.java:9924)
[22:59:49]:     at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
[22:59:49]:     ... 48 more
[22:59:49]: Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
[22:59:49]:     at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:80)
[22:59:49]:     at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:296)
[22:59:49]:     at java.lang.Thread.run(Unknown Source)
`

**Comment by Wolfsblvt** [comment]
Yeah, bug is known and already mentioned at #397.
