### ISSUE TITLE
Google Authentication Failing

### ISSUE THREAD

**Issue by rcf22** [Wolfsblvt/BlossomsPokemonGoManager#430]
I had the app working a couple days ago, but I'm encountering some exceptions when attempting to authenticate now. Any idea what could be causing this? Stack trace copied below.

`[21:44:46]: D/GoogleUserCredentialProvider: 3600
[21:44:46]: D/GoogleUserCredentialProvider: Got token: **xxxxxxxxxxxxxxxxxxxxx**
[21:44:48]: D/RequestHandler: Authenticated with static token
[21:44:49]: Exception in thread "AWT-EventQueue-0" [21:44:49]: com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
[21:44:49]:     at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:46)
[21:44:49]:     at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
[21:44:49]:     at com.pokegoapi.api.PokemonGo.fireRequestBlockOne(PokemonGo.java:210)
[21:44:49]:     at com.pokegoapi.api.PokemonGo.initialize(PokemonGo.java:168)
[21:44:49]:     at com.pokegoapi.api.PokemonGo.login(PokemonGo.java:164)
[21:44:49]:     at me.corriekay.pokegoutil.data.managers.AccountController.logOn(AccountController.java:218)
[21:44:49]:     at me.corriekay.pokegoutil.BlossomsPoGoManager$1.run(BlossomsPoGoManager.java:55)
[21:44:49]:     at java.awt.event.InvocationEvent.dispatch(Unknown Source)
[21:44:49]:     at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[21:44:49]:     at java.awt.EventQueue.access$500(Unknown Source)
[21:44:49]:     at java.awt.EventQueue$3.run(Unknown Source)
[21:44:49]:     at java.awt.EventQueue$3.run(Unknown Source)
[21:44:49]:     at java.security.AccessController.doPrivileged(Native Method)
[21:44:49]:     at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[21:44:49]:     at java.awt.EventQueue.dispatchEvent(Unknown Source)
[21:44:49]:     at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[21:44:49]:     at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[21:44:49]:     at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[21:44:49]:     at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[21:44:49]:     at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[21:44:49]:     at java.awt.EventDispatchThread.run(Unknown Source)
[21:44:49]: Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
[21:44:49]:     at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
[21:44:49]:     at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
[21:44:49]:     at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
[21:44:49]:     at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:38)
[21:44:49]:     ... 20 more
[21:44:49]: Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
[21:44:49]:     at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
[21:44:49]:     at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
[21:44:49]:     at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
[21:44:49]:     at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
[21:44:49]:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
[21:44:49]:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[21:44:49]:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
[21:44:49]:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[21:44:49]:     at rx.Observable.subscribe(Observable.java:9957)
[21:44:49]:     at rx.Observable.subscribe(Observable.java:9924)
[21:44:49]:     at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
[21:44:49]:     ... 22 more
[21:44:49]: Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
[21:44:49]:     at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:80)
[21:44:49]:     at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:296)
[21:44:49]:     at java.lang.Thread.run(Unknown Source)
`

**Comment by Wolfsblvt** [comment]
You shouldn't post your token here, unless you want people to login with your acount :P 

Yes, those are the "normal" exceptions for login issues via google. Don't know if there is much to do then trying again.
I have implemented a new Google Login way that will come with the next version.

Is it working to login after a few tries?

**Comment by rcf22** [comment]
Woops, thanks.

I've tried 2-3 times per day the last two days with no successful logins. I'll look forward to trying the new login mechanism when that is available. Appreciate the work you've done on this tool.

**Comment by Wolfsblvt** [comment]
I've implemented the newest login mechanism. And most problems with login errors are based on using a VPN or a proxy.

Is this issue still valid here? Going to close that for now.
