### ISSUE TITLE
Ditto throws NullPointerException

### ISSUE THREAD

**Issue by Wolfsblvt** [Wolfsblvt/BlossomsPokemonGoManager#489]
When ditto is part of the pokémon collection, BPGM throws an exception.

```
[20:20:12]: java.lang.NullPointerException
[20:20:12]: at me.corriekay.pokegoutil.utils.pokemon.PokemonCalculationUtils.dpsForMove(PokemonCalculationUtils.java:89)
[20:20:12]: at me.corriekay.pokegoutil.utils.pokemon.PokemonCalculationUtils.dpsForMove(PokemonCalculationUtils.java:75)
[20:20:12]: at me.corriekay.pokegoutil.data.enums.PokeColumn$13.get(PokeColumn.java:106)
[20:20:12]: at me.corriekay.pokegoutil.utils.windows.PokemonTableModel.lambda$updateTableData$0(PokemonTableModel.java:48)
[20:20:12]: at java.util.ArrayList.forEach(ArrayList.java:1249)
[20:20:12]: at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2062)
[20:20:12]: at me.corriekay.pokegoutil.utils.windows.PokemonTableModel.updateTableData(PokemonTableModel.java:43)
[20:20:12]: at me.corriekay.pokegoutil.utils.windows.PokemonTable.constructNewTableModel(PokemonTable.java:108)
[20:20:12]: at me.corriekay.pokegoutil.windows.PokemonTab.refreshList(PokemonTab.java:1040)
[20:20:12]: at me.corriekay.pokegoutil.windows.PokemonTab.lambda$new$10(PokemonTab.java:248)
[20:20:12]: at me.corriekay.pokegoutil.utils.helpers.LDocumentListener$1.lambda$changedUpdate$0(LDocumentListener.java:58)
[20:20:12]: at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
[20:20:12]: at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
[20:20:12]: at java.awt.EventQueue.access$500(EventQueue.java:97)
[20:20:12]: at java.awt.EventQueue$3.run(EventQueue.java:709)
[20:20:12]: at java.awt.EventQueue$3.run(EventQueue.java:703)
[20:20:12]: at java.security.AccessController.doPrivileged(Native Method)
[20:20:12]: at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
[20:20:12]: at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
[20:20:12]: at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
[20:20:12]: at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
[20:20:12]: at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
[20:20:12]: at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[20:20:12]: at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
[20:20:12]: at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
[20:20:17]: Saved queried locations to file.

```

Mentioned here: https://www.reddit.com/r/pokemongodev/comments/5eeafs/is_blossoms_pogo_manager_working_for_you_guys/dabtqo4/?context=3

**Comment by Wolfsblvt** [comment]
Duplicate of #490.
