### ISSUE TITLE
Cant use today

### ISSUE THREAD

**Issue by fathong724** [Wolfsblvt/BlossomsPokemonGoManager#494]
As shown
![001](https://cloud.githubusercontent.com/assets/23455301/20568856/d3f7436a-b1d8-11e6-8e8a-4864fcc7e858.jpg)
with these wordings

[23:53:20]: java.lang.NullPointerException
[23:53:20]: 	at me.corriekay.pokegoutil.utils.pokemon.PokemonCalculationUtils.dpsForMove(PokemonCalculationUtils.java:89)
[23:53:20]: 	at me.corriekay.pokegoutil.utils.pokemon.PokemonCalculationUtils.dpsForMove(PokemonCalculationUtils.java:75)
[23:53:20]: 	at me.corriekay.pokegoutil.data.enums.PokeColumn$13.get(PokeColumn.java:106)
[23:53:20]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTableModel.lambda$updateTableData$0(PokemonTableModel.java:48)
[23:53:20]: 	at java.util.ArrayList.forEach(Unknown Source)
[23:53:20]: 	at java.util.Collections$SynchronizedCollection.forEach(Unknown Source)
[23:53:20]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTableModel.updateTableData(PokemonTableModel.java:43)
[23:53:20]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTable.constructNewTableModel(PokemonTable.java:108)
[23:53:20]: 	at me.corriekay.pokegoutil.windows.PokemonTab.refreshList(PokemonTab.java:1040)
[23:53:20]: 	at me.corriekay.pokegoutil.windows.PokemonTab.lambda$new$10(PokemonTab.java:248)
[23:53:20]: 	at me.corriekay.pokegoutil.utils.helpers.LDocumentListener$1.lambda$changedUpdate$0(LDocumentListener.java:58)
[23:53:20]: 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
[23:53:20]: 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[23:53:20]: 	at java.awt.EventQueue.access$500(Unknown Source)
[23:53:20]: 	at java.awt.EventQueue$3.run(Unknown Source)
[23:53:20]: 	at java.awt.EventQueue$3.run(Unknown Source)
[23:53:20]: 	at java.security.AccessController.doPrivileged(Native Method)
[23:53:20]: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[23:53:20]: 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[23:53:20]: 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[23:53:20]: 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[23:53:20]: 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[23:53:20]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[23:53:20]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[23:53:20]: 	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Wolfsblvt** [comment]
You caught Ditto.
Bug is already fixed and will be shipped soon.

Duplicate of #490.

**Comment by micah-or-meekah** [comment]
In response to this, what do you mean "will be shipped soon"?

Does this mean a new version of the manager will be available? 

Thanks
