### ISSUE TITLE
Suddenly getting error after logged in

### ISSUE THREAD

**Issue by tangrl** [Wolfsblvt/BlossomsPokemonGoManager#497]
Just got the following error after logged in. Was OK last night.

14:58:33]: java.lang.NullPointerException
[14:58:33]: 	at me.corriekay.pokegoutil.utils.pokemon.PokemonCalculationUtils.dpsForMove(PokemonCalculationUtils.java:89)
[14:58:33]: 	at me.corriekay.pokegoutil.utils.pokemon.PokemonCalculationUtils.dpsForMove(PokemonCalculationUtils.java:75)
[14:58:33]: 	at me.corriekay.pokegoutil.data.enums.PokeColumn$13.get(PokeColumn.java:106)
[14:58:33]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTableModel.lambda$updateTableData$0(PokemonTableModel.java:48)
[14:58:33]: 	at java.util.ArrayList.forEach(Unknown Source)
[14:58:33]: 	at java.util.Collections$SynchronizedCollection.forEach(Unknown Source)
[14:58:33]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTableModel.updateTableData(PokemonTableModel.java:43)
[14:58:33]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTable.constructNewTableModel(PokemonTable.java:108)
[14:58:33]: 	at me.corriekay.pokegoutil.windows.PokemonTab.refreshList(PokemonTab.java:1040)
[14:58:33]: 	at me.corriekay.pokegoutil.windows.PokemonTab.lambda$new$10(PokemonTab.java:248)
[14:58:33]: 	at me.corriekay.pokegoutil.utils.helpers.LDocumentListener$1.lambda$changedUpdate$0(LDocumentListener.java:58)
[14:58:33]: 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
[14:58:33]: 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[14:58:33]: 	at java.awt.EventQueue.access$500(Unknown Source)
[14:58:33]: 	at java.awt.EventQueue$3.run(Unknown Source)
[14:58:33]: 	at java.awt.EventQueue$3.run(Unknown Source)
[14:58:33]: 	at java.security.AccessController.doPrivileged(Native Method)
[14:58:33]: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[14:58:33]: 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[14:58:33]: 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[14:58:33]: 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[14:58:33]: 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[14:58:33]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[14:58:33]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[14:58:33]: 	at java.awt.EventDispatchThread.run(Unknown Source)
[14:58:38]: Saved queried locations to file.

**Comment by tangrl** [comment]
Note that login was successful. Right before the error:

[15:02:22]: Successfully logged in. Welcome, abccdefg.
[15:02:22]: Stats: Lvl 30 Valor player.
[15:02:22]: Pokédex - Types Caught: 127, Total Pokémon Caught: 6679, Total Current Pokémon: 341 (+9 Eggs)
[15:02:22]: Current version: v0.1.4
[15:02:22]: Latest version from server: v0.1.4
[15:02:22]: Highest Duel Ability: Snorlax with Lick and Hyper Beam has 21209394375
[15:02:22]: Highest Gym Offense: Dragonite with Dragon Breath and Hyper Beam has 467062.5
[15:02:22]: Highest Gym Defense: Lapras with Ice Shard and Ice Beam has 9490026563
[15:02:22]: Load saved locations from file.

**Comment by SarkasB** [comment]
Did you catch a Ditto? It seems to cause trouble because of its 0 move. Nobody ever catched one before this event it seems.

**Comment by tangrl** [comment]
Yes, I just caught a Ditto!

**Comment by tangrl** [comment]
Can we have it fixed soon please? Really want to take advantage of the double XP double stardust event? Thanks in advance!

**Comment by micah-or-meekah** [comment]
It's being fixed. Just need to wait for the rollout of the new version of the manager. I also encountered the error.

**Comment by mdnpascual** [comment]
I think it's already fixed on src code, just need to compile yourself or put another release. I just managed to run in an IDE, don't know how to compile it with eclipse

**Comment by gruberc** [comment]
Yeah, I don't know how to compile, so I have to wait patiently or trash my ditto

**Comment by Wolfsblvt** [comment]
Guys, you keep stressing me \*lol\* This is like the tenth bug report and I am already working hard for a new clean release soon xD

You will get your working version until tomorrow.

Duplicate of #489.

**Comment by gruberc** [comment]
Thanks Wolfsblvt! I don't know anyone that knows of this app in my communities, but I am so glad this app exists. By far the greatest app for POGO! You rock!

**Comment by Wolfsblvt** [comment]
Thank you (:
