### ISSUE TITLE
Generation 2 pokemon hatched and App stopped working

### ISSUE THREAD

**Issue by tangrl** [Wolfsblvt/BlossomsPokemonGoManager#517]
Pichu was hatched tonight and I can no longer open the application. It's 93% IV, hate to transfer.

[23:31:59]: java.lang.NullPointerException
[23:31:59]: 	at com.pokegoapi.api.pokemon.PokemonDetails.getPokemonFamily(PokemonDetails.java:39)
[23:31:59]: 	at me.corriekay.pokegoutil.windows.PokemonTab.lambda$refreshList$17(PokemonTab.java:1014)
[23:31:59]: 	at java.util.ArrayList.forEach(Unknown Source)
[23:31:59]: 	at java.util.Collections$SynchronizedCollection.forEach(Unknown Source)
[23:31:59]: 	at me.corriekay.pokegoutil.windows.PokemonTab.refreshList(PokemonTab.java:1008)
[23:31:59]: 	at me.corriekay.pokegoutil.windows.PokemonTab.lambda$new$10(PokemonTab.java:249)
[23:31:59]: 	at me.corriekay.pokegoutil.utils.helpers.LDocumentListener$1.lambda$changedUpdate$0(LDocumentListener.java:58)
[23:31:59]: 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
[23:31:59]: 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[23:31:59]: 	at java.awt.EventQueue.access$500(Unknown Source)
[23:31:59]: 	at java.awt.EventQueue$3.run(Unknown Source)
[23:31:59]: 	at java.awt.EventQueue$3.run(Unknown Source)
[23:31:59]: 	at java.security.AccessController.doPrivileged(Native Method)
[23:31:59]: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[23:31:59]: 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[23:31:59]: 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[23:31:59]: 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[23:31:59]: 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[23:31:59]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[23:31:59]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[23:31:59]: 	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Gnomuz** [comment]
Same bug here, as a piece of information I have already hatched a Cleffa (Gen2 baby)

**Comment by Creeker5** [comment]
Same issue with my Cleffa

**Comment by iamsoedwin** [comment]
Same issue here with my recently hatched Elekid as well

**Comment by lionelmagen** [comment]
yes thx @hydrogeny 

no issue, damn :/

**Comment by Wolfsblvt** [comment]
I could see if I can implement a hotfix where the new Pokémon are just hidden, so that the tool for the old ones still work.
Untill the API gets updated of course.

**Comment by Hydrogeny** [comment]
That would be great! Starting to panic here :p 
Is it a difficult problem or just loads of work? Perhaps we (i) can help?

**Comment by lionelmagen** [comment]
ok :) waiting for that so haha 
thx for answering

**Comment by Wolfsblvt** [comment]
The real issue lies within the [Grover-c13/PokeGOAPI-Java](https://github.com/Grover-c13/PokeGOAPI-Java). It needs to be updated with all the new Pokémon data.
They have Meta files with moveset info, attack times, base stats, etc etc etc. And all of those files need to get updated, so that the Pokémon has the meta itself, but also its moves exist there, and it's family is updated...

For the few new babies that shouldn't be **that** much of work, just a bit manual inputting of data in a few files, but sadly I do not have the time and will to dive into this API at the moment.

**Comment by lionelmagen** [comment]
thx Wolf

**Comment by Hydrogeny** [comment]
If you have an examlpe of what should be editted in the files i can help. Ig its not the much work to explain ill fix the files for now.

**Comment by Wolfsblvt** [comment]
If it wouldn't be much work, I would to it myself, so it's obviously a bit more to figure everything out :P 

[This is the main Meta file](https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/api/pokemon/PokemonMetaRegistry.java#L32-L73) where all the Pokémon are defined. I have highlighted a block.
The API needs data there for all the new Pokémon. That means the Protos must be updated too though, cause the new PokemonIds are missing. And there's a new familyId for Togepi, right?

If there are new moves, the PokemonMoveMetaRegistry has to be updated too

**Comment by vidoardes** [comment]
@Wolfsblvt Do you know where they get that data to fill it from? I'm not adverse to updating the file by hand

**Comment by Wolfsblvt** [comment]
From [here](https://gist.github.com/alucas/6db8f10aa888055cc11492e32077fb90) or [here](https://github.com/celandro/pokebattler-fight/blob/master/src/main/resources/com/pokebattler/fight/data/pokemongo.json). Those are the new dumps of the official game protos.

But yeah, doesn't help if you can't figure out how to update the base protos and if their project isn't updated. I have learned that a month ago, but forgot it already again xD
There must be an issue or info somewhere on the API GitHub.

**Comment by lionelmagen** [comment]
@Wolfsblvt  plz wolf, dont understand all the purpose. did they fix it ? thx

**Comment by Wolfsblvt** [comment]
@lionelmagen Nope, still not implemented.

**Comment by lionelmagen** [comment]
thx :))

**Comment by Ajit1000** [comment]
Thanks for the efforts put in Wolf, please do the updates or release a beta version (as you mentioned above ... ignoring new Pokemons) while you fix the rest of meta file/database. Running out of bag space also, 7th day streak coming, need to use my lucky egg and do an evolve spree 😉

**Comment by vidoardes** [comment]
@Ajit1000 there is a beta version available on the Discord channel that filters out the Gen II babies as a temp workaround

**Comment by schagnon** [comment]
Link?

**Comment by Wolfsblvt** [comment]
Discord server is linked on top of the GitHub repo here. The download is stickied in the general channel.

But the hotfix will be released officially soon too.

**Comment by RGinCanada** [comment]
Is there a Paypal account that we can contribute to to help compensate for the time and effort put into this tool? I use it all the time, and would be happy to donate.

**Comment by Wolfsblvt** [comment]
Yeah, explained it here: #508

**Comment by Wolfsblvt** [comment]
Oki, new version is released an this issue should be fixed with a temporary workaround (:

**Comment by Creeker5** [comment]
Thank you so much!

**Comment by Ajit1000** [comment]
Bless you! Wolf, you made my day. I was almost on verge of giving up and starting afresh. I am @ level 32 was thinking of starting from beginning ... 7,50,000 XP?!! I was weighing it against level 20 🤔

**Comment by schagnon** [comment]
With 500k to level I'm contemplating end game.  Thank god we have these pathetic baby's to hatch from eggs to save my desire to endure the 5 degree temps.  :)
