### ISSUE TITLE
Blossom doesnt work

### ISSUE THREAD

**Issue by lionelmagen** [Wolfsblvt/BlossomsPokemonGoManager#520]
Hi, 

since update with baby pokemon, blossom doest launch
any issue ? 

thx for help

here the message : 

[14:17:55]: Latest version from server: v0.1.5
[14:17:55]: java.lang.NullPointerException
[14:17:55]: 	at com.pokegoapi.api.pokemon.PokemonDetails.getPokemonFamily(PokemonDetails.java:39)
[14:17:55]: 	at me.corriekay.pokegoutil.windows.PokemonTab.lambda$refreshList$17(PokemonTab.java:1014)
[14:17:55]: 	at java.util.ArrayList.forEach(Unknown Source)
[14:17:55]: 	at java.util.Collections$SynchronizedCollection.forEach(Unknown Source)
[14:17:55]: 	at me.corriekay.pokegoutil.windows.PokemonTab.refreshList(PokemonTab.java:1008)
[14:17:55]: 	at me.corriekay.pokegoutil.windows.PokemonTab.lambda$new$10(PokemonTab.java:249)
[14:17:55]: 	at me.corriekay.pokegoutil.utils.helpers.LDocumentListener$1.lambda$changedUpdate$0(LDocumentListener.java:58)
[14:17:55]: 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
[14:17:55]: 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[14:17:55]: 	at java.awt.EventQueue.access$500(Unknown Source)
[14:17:55]: 	at java.awt.EventQueue$3.run(Unknown Source)
[14:17:55]: 	at java.awt.EventQueue$3.run(Unknown Source)
[14:17:55]: 	at java.security.AccessController.doPrivileged(Native Method)
[14:17:55]: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[14:17:55]: 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[14:17:55]: 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[14:17:55]: 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[14:17:55]: 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[14:17:55]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[14:17:55]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[14:17:55]: 	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Hydrogeny** [comment]
https://github.com/Wolfsblvt/BlossomsPokemonGoManager/issues/517

**Comment by Wolfsblvt** [comment]
Yeah. Next time at least **look** at the most recent issues here on github :P 
I even made a new label, just so that people don't overlook it:

![Image](http://i.imgur.com/dDJwTvF.png)


It's this: #517
