### ISSUE TITLE
Displaying pokemon when searching but blank otherwise

### ISSUE THREAD

**Issue by leelkennedy** [Wolfsblvt/BlossomsPokemonGoManager#521]
It started up like normal but no pokemon are showing in the app. If I search, it will display those that match the search, but nothing else.

Logs below:
`[12/14 18:43:02]: java.lang.NullPointerException
[12/14 18:43:02]: 	at me.corriekay.pokegoutil.windows.PokemonTab$PokemonTableModel.lambda$0(PokemonTab.java:395)
[12/14 18:43:02]: 	at java.util.ArrayList.forEach(Unknown Source)
[12/14 18:43:02]: 	at me.corriekay.pokegoutil.windows.PokemonTab$PokemonTableModel.<init>(PokemonTab.java:379)
[12/14 18:43:02]: 	at me.corriekay.pokegoutil.windows.PokemonTab$PokemonTableModel.<init>(PokemonTab.java:376)
[12/14 18:43:02]: 	at me.corriekay.pokegoutil.windows.PokemonTab$PokemonTable.constructNewTableModel(PokemonTab.java:327)
[12/14 18:43:02]: 	at me.corriekay.pokegoutil.windows.PokemonTab$PokemonTable.access$1(PokemonTab.java:326)
[12/14 18:43:02]: 	at me.corriekay.pokegoutil.windows.PokemonTab.refreshList(PokemonTab.java:285)
[12/14 18:43:02]: 	at me.corriekay.pokegoutil.windows.PokemonTab.lambda$4(PokemonTab.java:90)
[12/14 18:43:02]: 	at me.corriekay.pokegoutil.utils.LDocumentListener$1.lambda$0(LDocumentListener.java:51)
[12/14 18:43:02]: 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
[12/14 18:43:02]: 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[12/14 18:43:02]: 	at java.awt.EventQueue.access$500(Unknown Source)
[12/14 18:43:02]: 	at java.awt.EventQueue$3.run(Unknown Source)
[12/14 18:43:02]: 	at java.awt.EventQueue$3.run(Unknown Source)
[12/14 18:43:02]: 	at java.security.AccessController.doPrivileged(Native Method)
[12/14 18:43:02]: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[12/14 18:43:02]: 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[12/14 18:43:02]: 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[12/14 18:43:02]: 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[12/14 18:43:02]: 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[12/14 18:43:02]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[12/14 18:43:02]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[12/14 18:43:02]: 	at java.awt.EventDispatchThread.run(Unknown Source)
`

**Comment by schagnon** [comment]
Please close as #517 is covering this issue.
