### ISSUE TITLE
[Breaking Update]API Changes - App will not login

### ISSUE THREAD

**Issue by dnuzum** [Wolfsblvt/BlossomsPokemonGoManager#541]
Looks like the API changes have also broken BPGM just like many other apps. In-app console output below. This is using Google OAuth token copy/paste.
```[20:11:54]: Successfully logged in. Welcome, dnuzum.
[20:11:54]: Stats: Lvl 22 Instinct player.
[20:11:54]: Pokédex - Types Caught: 111, Total Pokémon Caught: 1294, Total Current Pokémon: 169 (+9 Eggs)
[20:11:54]: Current version: v0.1.6
[20:11:54]: Latest version from server: v0.1.6
[20:11:54]: Highest Duel Ability: Snorlax with Lick and Hyper Beam has 23440494375
[20:11:54]: Highest Gym Offense: Alakazam with Psycho Cut and Psychic has 505862.5
[20:11:54]: Highest Gym Defense: Lapras with Ice Shard and Ice Beam has 9490026563
[20:11:54]: Load saved locations from file.
[20:11:54]: java.lang.NullPointerException
[20:11:54]: 	at me.corriekay.pokegoutil.utils.pokemon.PokemonCalculationUtils.dpsForMove(PokemonCalculationUtils.java:89)
[20:11:54]: 	at me.corriekay.pokegoutil.utils.pokemon.PokemonCalculationUtils.dpsForMove(PokemonCalculationUtils.java:75)
[20:11:54]: 	at me.corriekay.pokegoutil.data.enums.PokeColumn$13.get(PokeColumn.java:109)
[20:11:54]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTableModel.lambda$updateTableData$1(PokemonTableModel.java:51)
[20:11:54]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[20:11:54]: 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[20:11:54]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
[20:11:54]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
[20:11:54]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[20:11:54]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[20:11:54]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[20:11:54]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[20:11:54]: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
[20:11:54]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTableModel.updateTableData(PokemonTableModel.java:46)
[20:11:54]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTable.constructNewTableModel(PokemonTable.java:108)
[20:11:54]: 	at me.corriekay.pokegoutil.windows.PokemonTab.refreshList(PokemonTab.java:1045)
[20:11:54]: 	at me.corriekay.pokegoutil.windows.PokemonTab.lambda$new$10(PokemonTab.java:249)
[20:11:54]: 	at me.corriekay.pokegoutil.utils.helpers.LDocumentListener$1.lambda$changedUpdate$0(LDocumentListener.java:58)
[20:11:54]: 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
[20:11:54]: 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
[20:11:54]: 	at java.awt.EventQueue.access$500(EventQueue.java:97)
[20:11:54]: 	at java.awt.EventQueue$3.run(EventQueue.java:709)
[20:11:54]: 	at java.awt.EventQueue$3.run(EventQueue.java:703)
[20:11:54]: 	at java.security.AccessController.doPrivileged(Native Method)
[20:11:54]: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
[20:11:54]: 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
[20:11:54]: 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
[20:11:54]: 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
[20:11:54]: 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
[20:11:54]: 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[20:11:54]: 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
[20:11:54]: 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)```

**Comment by moose-cove** [comment]
Seeing the same thing on my end as well.

**Comment by plebicidal** [comment]
also same :(

**Comment by GCHarald** [comment]
me too

**Comment by mtressl** [comment]
Works for me, just refreshed my list.
[11:21:18]: Done refreshing Pokémon list

**Comment by thisischrys** [comment]
Latest release and build from dev both still working here. Probably not showing new pokemon.

**Comment by GCHarald** [comment]
Not for me. I tried it with an account without any new Pokemons.

Update: With some accounts I have no problems (including new Pokemons which won't be shown) and with some accounts it won't work!

**Comment by Chazn2** [comment]
Probably crashing for the same reason baby pokemon broke things.

**Comment by mtressl** [comment]
Now I got the error as well. #bummer

**Comment by austin987** [comment]
Failing for me with the last release (0.1.6), and development HEAD (currently 410c9f25712eef37599fd9fb994ed8e012f892ea)

**Comment by ghost** [comment]
Same here, new API breaks things up I guess.

**Comment by Wolfsblvt** [comment]
NullPointerException in that case is when new moves are added but are not added in BPGM.
That should be an issue with v0.1.6 release, but not with the current dev version anymore.

Is the dev branch failing with the same stacktrace?

**Comment by dawnforge** [comment]
Not sure what steps are needed to update my current install to the dev branch, but I would be willing to give it a try. Does it need to be built or just have files replaced?

**Comment by austin987** [comment]
@Wolfsblvt, I built 410c9f25712eef37599fd9fb994ed8e012f892ea and see what appears to be the same crash. Attached.
[develop.txt](https://github.com/Wolfsblvt/BlossomsPokemonGoManager/files/785515/develop.txt)

**Comment by Hundyr** [comment]
Is there any way that end users can help if you don't have programming experience? I've been using BPGM for some time, as have many other players I know, and I absolutely love it. Is there info I/we can send to help? Do you have anywhere to accept donations? Do you need people to test new builds? Thank you, and please let me know if there's anything I can do to help as an end user.

**Comment by theoriginaljester** [comment]
BPGM continued to work even after I had updated the game.  I caught about 10+ 2nd gen pokemon (Excluding babies) and BPGM worked fine and treated them as the baby pokemon.  I tried again today but it is of no more.  I'm not sure if the moves, attack durations, and new items and ect. all changed within the same update but if not... maybe there was a server side change?   Honestly no idea how updates work other than I install them and things change... But i've seen things change without updating so I'm just... confused.

**Comment by RzBoxy** [comment]
My old account can login because there is no Gen2 pokemon

**Comment by Cassolotl** [comment]
I'm in the same situation as @theoriginaljester - BPGM kept working for me after I'd *caught* quite a few Gen 2 pokemon. And then while I was in the middle of an evolution session using BPGM, I clicked reload and it broke.

The one pokemon I evolved into a Gen 2 was Golbat to Crobat, if that's any help!

**Comment by kribjo** [comment]
It has been stated in a comment on a related bug:
As soon as you have a 'mon with a move that BPGM does not know, it throws this error. You can have as many gen 2 pokémons you want, they will just be ignored until one of them has an "unknown" move, *then* BPGM breaks.
https://github.com/Wolfsblvt/BlossomsPokemonGoManager/issues/546#issuecomment-280826858

**Comment by RBuenemann** [comment]
Do we have an eta on a new version release? Is it going to be 0.1.7 or 0.2.0 for gen 2 being included?

**Comment by ghost** [comment]
@kribjo is correct, I had two pokemon that had new moves. I had a Gastly with a new move, transferred him. New Pinsir had another new move, wasn't willing to transfer.

The issue is hit in the two methods: weaveDps and dpsForMove. A temporary fix (only to get passed the issue) was to change the UNRECOGNIZED move to a generic move and the NULL moveMeta to return a dps of -1.

Now BPGM is working enough so I can do a mass evolve.

**Comment by Hundyr** [comment]
I haven't seen this mentioned, but previously existing moves such as Aqua Tail and Water Pulse have been changed. I assume this would mean that even having Gen 1 Pokemon with altered moves would/could cause the problem being seen.

**Comment by austin987** [comment]
FWIW, on the upstream PogoAPI-Java bug gegy1000 says he has it working in his fork: https://github.com/Grover-c13/PokeGOAPI-Java/issues/863#issuecomment-280925889

I tried building the develop branch with his api branch:
```
diff --git a/pom.xml b/pom.xml
index 900e91d..0a6e87f 100644
--- a/pom.xml
+++ b/pom.xml
@@ -105,9 +105,9 @@
             <!--<version>0.4.1</version>-->
         <!--</dependency>-->
         <dependency>
-            <groupId>com.github.Grover-c13</groupId>
+            <groupId>com.github.gegy1000</groupId>
             <artifactId>PokeGOAPI-Java</artifactId>
-            <version>7317a049fe3cbb38e219e0056c21b29505133db4</version>
+            <version>66bc865e03985beda481be92749f4e3acaff0e92</version>
         </dependency>
 <!--         <dependency> -->
 <!--             <groupId>com.github.Wolfsblvt</groupId> -->
```

which compiles, but it breaks the unit tests:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running test.me.corriekay.pokegoutil.gui.controller.LogControllerTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.674 sec - in test.me.corriekay.pokegoutil.gui.controller.LogControllerTest
Running me.corriekay.pokegoutil.data.models.operations.TransferOperationTest
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.228 sec <<< FAILURE! - in me.corriekay.pokegoutil.data.models.operations.TransferOperationTest
pokemonIsInGym(me.corriekay.pokegoutil.data.models.operations.TransferOperationTest)  Time elapsed: 0.225 sec  <<< ERROR!
java.lang.NoClassDefFoundError: com/pokegoapi/api/pokemon/PokemonMeta
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.mockito.cglib.core.ReflectUtils.addAllMethods(ReflectUtils.java:349)
	at org.mockito.cglib.proxy.Enhancer.getMethods(Enhancer.java:422)
	at org.mockito.cglib.proxy.Enhancer.generateClass(Enhancer.java:457)
	at org.mockito.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:217)
	at org.mockito.cglib.proxy.Enhancer.createHelper(Enhancer.java:378)
	at org.mockito.cglib.proxy.Enhancer.createClass(Enhancer.java:318)
	at org.mockito.internal.creation.cglib.ClassImposterizer.createProxyClass(ClassImposterizer.java:123)
	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:57)
	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:49)
	at org.mockito.internal.creation.cglib.CglibMockMaker.createMock(CglibMockMaker.java:24)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
	at org.mockito.Mockito.mock(Mockito.java:1285)
	at org.mockito.Mockito.mock(Mockito.java:1163)
	at me.corriekay.pokegoutil.data.models.operations.TransferOperationTest.beforeTest(TransferOperationTest.java:33)

sucessfullyTransfer(me.corriekay.pokegoutil.data.models.operations.TransferOperationTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: com/pokegoapi/api/pokemon/PokemonMeta
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.mockito.cglib.core.ReflectUtils.addAllMethods(ReflectUtils.java:349)
	at org.mockito.cglib.proxy.Enhancer.getMethods(Enhancer.java:422)
	at org.mockito.cglib.proxy.Enhancer.generateClass(Enhancer.java:457)
	at org.mockito.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:217)
	at org.mockito.cglib.proxy.Enhancer.createHelper(Enhancer.java:378)
	at org.mockito.cglib.proxy.Enhancer.createClass(Enhancer.java:318)
	at org.mockito.internal.creation.cglib.ClassImposterizer.createProxyClass(ClassImposterizer.java:123)
	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:57)
	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:49)
	at org.mockito.internal.creation.cglib.CglibMockMaker.createMock(CglibMockMaker.java:24)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
	at org.mockito.Mockito.mock(Mockito.java:1285)
	at org.mockito.Mockito.mock(Mockito.java:1163)
	at me.corriekay.pokegoutil.data.models.operations.TransferOperationTest.beforeTest(TransferOperationTest.java:33)

pokemonIsFavorite(me.corriekay.pokegoutil.data.models.operations.TransferOperationTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.NoClassDefFoundError: com/pokegoapi/api/pokemon/PokemonMeta
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.mockito.cglib.core.ReflectUtils.addAllMethods(ReflectUtils.java:349)
	at org.mockito.cglib.proxy.Enhancer.getMethods(Enhancer.java:422)
	at org.mockito.cglib.proxy.Enhancer.generateClass(Enhancer.java:457)
	at org.mockito.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:217)
	at org.mockito.cglib.proxy.Enhancer.createHelper(Enhancer.java:378)
	at org.mockito.cglib.proxy.Enhancer.createClass(Enhancer.java:318)
	at org.mockito.internal.creation.cglib.ClassImposterizer.createProxyClass(ClassImposterizer.java:123)
	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:57)
	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:49)
	at org.mockito.internal.creation.cglib.CglibMockMaker.createMock(CglibMockMaker.java:24)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
	at org.mockito.Mockito.mock(Mockito.java:1285)
	at org.mockito.Mockito.mock(Mockito.java:1163)
	at me.corriekay.pokegoutil.data.models.operations.TransferOperationTest.beforeTest(TransferOperationTest.java:33)

Running me.corriekay.pokegoutil.data.models.operations.OperationTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.069 sec - in me.corriekay.pokegoutil.data.models.operations.OperationTest
Running me.corriekay.pokegoutil.data.models.operations.EvolveOperationTest
Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.003 sec <<< FAILURE! - in me.corriekay.pokegoutil.data.models.operations.EvolveOperationTest
sucessfullyEvolve(me.corriekay.pokegoutil.data.models.operations.EvolveOperationTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: com/pokegoapi/api/pokemon/PokemonMeta
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.mockito.cglib.core.ReflectUtils.addAllMethods(ReflectUtils.java:349)
	at org.mockito.cglib.proxy.Enhancer.getMethods(Enhancer.java:422)
	at org.mockito.cglib.proxy.Enhancer.generateClass(Enhancer.java:457)
	at org.mockito.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:217)
	at org.mockito.cglib.proxy.Enhancer.createHelper(Enhancer.java:378)
	at org.mockito.cglib.proxy.Enhancer.createClass(Enhancer.java:318)
	at org.mockito.internal.creation.cglib.ClassImposterizer.createProxyClass(ClassImposterizer.java:123)
	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:57)
	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:49)
	at org.mockito.internal.creation.cglib.CglibMockMaker.createMock(CglibMockMaker.java:24)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
	at org.mockito.Mockito.mock(Mockito.java:1285)
	at org.mockito.Mockito.mock(Mockito.java:1163)
	at me.corriekay.pokegoutil.data.models.operations.EvolveOperationTest.beforeTest(EvolveOperationTest.java:34)

pokemonIsNotEvolvable(me.corriekay.pokegoutil.data.models.operations.EvolveOperationTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: com/pokegoapi/api/pokemon/PokemonMeta
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.mockito.cglib.core.ReflectUtils.addAllMethods(ReflectUtils.java:349)
	at org.mockito.cglib.proxy.Enhancer.getMethods(Enhancer.java:422)
	at org.mockito.cglib.proxy.Enhancer.generateClass(Enhancer.java:457)
	at org.mockito.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:217)
	at org.mockito.cglib.proxy.Enhancer.createHelper(Enhancer.java:378)
	at org.mockito.cglib.proxy.Enhancer.createClass(Enhancer.java:318)
	at org.mockito.internal.creation.cglib.ClassImposterizer.createProxyClass(ClassImposterizer.java:123)
	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:57)
	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:49)
	at org.mockito.internal.creation.cglib.CglibMockMaker.createMock(CglibMockMaker.java:24)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
	at org.mockito.Mockito.mock(Mockito.java:1285)
	at org.mockito.Mockito.mock(Mockito.java:1163)
	at me.corriekay.pokegoutil.data.models.operations.EvolveOperationTest.beforeTest(EvolveOperationTest.java:34)

pokemonIsInGym(me.corriekay.pokegoutil.data.models.operations.EvolveOperationTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: com/pokegoapi/api/pokemon/PokemonMeta
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.mockito.cglib.core.ReflectUtils.addAllMethods(ReflectUtils.java:349)
	at org.mockito.cglib.proxy.Enhancer.getMethods(Enhancer.java:422)
	at org.mockito.cglib.proxy.Enhancer.generateClass(Enhancer.java:457)
	at org.mockito.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:217)
	at org.mockito.cglib.proxy.Enhancer.createHelper(Enhancer.java:378)
	at org.mockito.cglib.proxy.Enhancer.createClass(Enhancer.java:318)
	at org.mockito.internal.creation.cglib.ClassImposterizer.createProxyClass(ClassImposterizer.java:123)
	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:57)
	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:49)
	at org.mockito.internal.creation.cglib.CglibMockMaker.createMock(CglibMockMaker.java:24)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
	at org.mockito.Mockito.mock(Mockito.java:1285)
	at org.mockito.Mockito.mock(Mockito.java:1163)
	at me.corriekay.pokegoutil.data.models.operations.EvolveOperationTest.beforeTest(EvolveOperationTest.java:34)

notEnoughCandies(me.corriekay.pokegoutil.data.models.operations.EvolveOperationTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: com/pokegoapi/api/pokemon/PokemonMeta
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.mockito.cglib.core.ReflectUtils.addAllMethods(ReflectUtils.java:349)
	at org.mockito.cglib.proxy.Enhancer.getMethods(Enhancer.java:422)
	at org.mockito.cglib.proxy.Enhancer.generateClass(Enhancer.java:457)
	at org.mockito.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:217)
	at org.mockito.cglib.proxy.Enhancer.createHelper(Enhancer.java:378)
	at org.mockito.cglib.proxy.Enhancer.createClass(Enhancer.java:318)
	at org.mockito.internal.creation.cglib.ClassImposterizer.createProxyClass(ClassImposterizer.java:123)
	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:57)
	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:49)
	at org.mockito.internal.creation.cglib.CglibMockMaker.createMock(CglibMockMaker.java:24)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
	at org.mockito.Mockito.mock(Mockito.java:1285)
	at org.mockito.Mockito.mock(Mockito.java:1163)
	at me.corriekay.pokegoutil.data.models.operations.EvolveOperationTest.beforeTest(EvolveOperationTest.java:34)

Running me.corriekay.pokegoutil.data.models.LoginDataTest
Tests run: 51, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.02 sec - in me.corriekay.pokegoutil.data.models.LoginDataTest

Results :

Tests in error: 
  TransferOperationTest.beforeTest:33 » NoClassDefFound com/pokegoapi/api/pokemo...
  TransferOperationTest.beforeTest:33 » NoClassDefFound com/pokegoapi/api/pokemo...
  TransferOperationTest.beforeTest:33 » NoClassDefFound com/pokegoapi/api/pokemo...
  EvolveOperationTest.beforeTest:34 » NoClassDefFound com/pokegoapi/api/pokemon/...
  EvolveOperationTest.beforeTest:34 » NoClassDefFound com/pokegoapi/api/pokemon/...
  EvolveOperationTest.beforeTest:34 » NoClassDefFound com/pokegoapi/api/pokemon/...
  EvolveOperationTest.beforeTest:34 » NoClassDefFound com/pokegoapi/api/pokemon/...

Tests run: 67, Failures: 0, Errors: 7, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.495 s
[INFO] Finished at: 2017-02-19T22:04:06-06:00
[INFO] Final Memory: 13M/209M
```

The tests do pass without that change, of course. So there will likely need to be some changes on Blossom's end as well for the new API.

**Comment by notoriouspeb** [comment]
Same Q as @hundyr. Thanks for a great tool 🙏Holler with how we can help! 🙌

**Comment by austin987** [comment]
Confirmed, thanks @Wolfsblvt
