### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 132, Size: 64

### ISSUE THREAD

**Issue by verydelight** [Wolfsblvt/BlossomsPokemonGoManager#543]
After doing some evolves I ended up with this in the log and the Pokemon list not working anymore in BPGM. Any ideas what caused the mess? TIA, OliverBonn
 
[18:28:59]: Evolving Magikarp. Evolve result: SUCCESS
[18:28:59]: Stat changes: (Candies: 78[477-400+1], CP: 1857[+1734], HP: 122[+90])
[18:29:00]: Waiting 4.187 seconds.
[18:29:04]: Doing Evolve 25 of 25
[18:29:06]: Evolving Kabuto. Evolve result: SUCCESS
[18:29:06]: Stat changes: (Candies: 37[86-50+1], CP: 1412[+761], HP: 79[+36])
[18:29:09]: java.lang.NullPointerException
[18:29:09]: 	at me.corriekay.pokegoutil.utils.pokemon.PokemonCalculationUtils.dpsForMove(PokemonCalculationUtils.java:89)
[18:29:09]: 	at me.corriekay.pokegoutil.utils.pokemon.PokemonCalculationUtils.dpsForMove(PokemonCalculationUtils.java:75)
[18:29:09]: 	at me.corriekay.pokegoutil.data.enums.PokeColumn$14.get(PokeColumn.java:116)
[18:29:09]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTableModel.lambda$updateTableData$1(PokemonTableModel.java:51)
[18:29:09]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[18:29:09]: 	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[18:29:09]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
[18:29:09]: 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[18:29:09]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[18:29:09]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[18:29:09]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[18:29:09]: 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[18:29:09]: 	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[18:29:09]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTableModel.updateTableData(PokemonTableModel.java:46)
[18:29:09]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTable.constructNewTableModel(PokemonTable.java:108)
[18:29:09]: 	at me.corriekay.pokegoutil.windows.PokemonTab.refreshList(PokemonTab.java:1045)
[18:29:09]: 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
[18:29:09]: 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[18:29:09]: 	at java.awt.EventQueue.access$500(Unknown Source)
[18:29:09]: 	at java.awt.EventQueue$3.run(Unknown Source)
[18:29:09]: 	at java.awt.EventQueue$3.run(Unknown Source)
[18:29:09]: 	at java.security.AccessController.doPrivileged(Native Method)
[18:29:09]: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[18:29:09]: 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[18:29:09]: 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[18:29:09]: 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[18:29:09]: 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[18:29:09]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[18:29:09]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[18:29:09]: 	at java.awt.EventDispatchThread.run(Unknown Source)
[18:29:15]: java.lang.IndexOutOfBoundsException: Index: 132, Size: 64
[18:29:15]: 	at java.util.ArrayList.rangeCheck(Unknown Source)
[18:29:15]: 	at java.util.ArrayList.get(Unknown Source)
[18:29:15]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTableModel.getValueAt(PokemonTableModel.java:93)
[18:29:15]: 	at javax.swing.JTable.getValueAt(Unknown Source)
[18:29:15]: 	at javax.swing.JTable.prepareRenderer(Unknown Source)
[18:29:15]: 	at javax.swing.JTable.getToolTipText(Unknown Source)
[18:29:15]: 	at javax.swing.ToolTipManager$insideTimerAction.actionPerformed(Unknown Source)
[18:29:15]: 	at javax.swing.Timer.fireActionPerformed(Unknown Source)
[18:29:15]: 	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
[18:29:15]: 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
[18:29:15]: 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[18:29:15]: 	at java.awt.EventQueue.access$500(Unknown Source)
[18:29:15]: 	at java.awt.EventQueue$3.run(Unknown Source)
[18:29:15]: 	at java.awt.EventQueue$3.run(Unknown Source)
[18:29:15]: 	at java.security.AccessController.doPrivileged(Native Method)
[18:29:15]: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[18:29:15]: 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[18:29:15]: 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[18:29:15]: 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[18:29:15]: 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[18:29:15]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[18:29:15]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[18:29:15]: 	at java.awt.EventDispatchThread.run(Unknown Source)
[18:29:31]: D/GoogleUserCredentialProvider: 3600
[18:29:31]: D/GoogleUserCredentialProvider: Refreshed Token 
[Token deleted by me]
[18:29:32]: D/RequestHandler: Authenticated with static token
[18:29:37]: Successfully logged in. Welcome, OliverBonn.
[18:29:37]: Stats: Lvl 30 Mystic player.
[18:29:37]: Pokédex - Types Caught: 146, Total Pokémon Caught: 5649, Total Current Pokémon: 261 (+9 Eggs)
[18:29:37]: Current version: v0.1.6
[18:29:37]: Latest version from server: v0.1.6
[18:29:37]: Highest Duel Ability: Snorlax with Lick and Hyper Beam has 23440494375
[18:29:37]: Highest Gym Offense: Alakazam with Psycho Cut and Psychic has 505862.5
[18:29:37]: Highest Gym Defense: Lapras with Ice Shard and Ice Beam has 9490026563
[18:29:37]: Load saved locations from file.
[18:29:37]: java.lang.NullPointerException
[and so on...]

**Comment by dwight-thinkbox** [comment]
I am getting the same, pasted below. I assume there was some change in the last few hours as it was working this morning. 

[16:10:50]: Successfully logged in. Welcome, xxx.
[16:10:51]: Stats: Lvl xx Valor player.
[16:10:51]: Pokédex - Types Caught: xx, Total Pokémon Caught: xx, Total Current Pokémon: xx (+9 Eggs)
[16:10:51]: Current version: v0.1.6
[16:10:51]: Latest version from server: v0.1.6
[16:10:51]: Highest Duel Ability: Snorlax with Lick and Hyper Beam has 23440494375
[16:10:51]: Highest Gym Offense: Alakazam with Psycho Cut and Psychic has 505862.5
[16:10:51]: Highest Gym Defense: Lapras with Ice Shard and Ice Beam has 9490026563
[16:10:51]: Load saved locations from file.
[16:10:51]: java.lang.NullPointerException
[16:10:51]: 	at me.corriekay.pokegoutil.utils.pokemon.PokemonCalculationUtils.dpsForMove(PokemonCalculationUtils.java:89)
[16:10:51]: 	at me.corriekay.pokegoutil.utils.pokemon.PokemonCalculationUtils.dpsForMove(PokemonCalculationUtils.java:75)
[16:10:51]: 	at me.corriekay.pokegoutil.data.enums.PokeColumn$14.get(PokeColumn.java:116)
[16:10:51]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTableModel.lambda$updateTableData$1(PokemonTableModel.java:51)
[16:10:51]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTableModel$$Lambda$94/26399314.accept(Unknown Source)
[16:10:51]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[16:10:51]: 	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[16:10:51]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
[16:10:51]: 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[16:10:51]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[16:10:51]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[16:10:51]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[16:10:51]: 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[16:10:51]: 	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[16:10:51]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTableModel.updateTableData(PokemonTableModel.java:46)
[16:10:51]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTable.constructNewTableModel(PokemonTable.java:108)
[16:10:51]: 	at me.corriekay.pokegoutil.windows.PokemonTab.refreshList(PokemonTab.java:1045)
[16:10:51]: 	at me.corriekay.pokegoutil.windows.PokemonTab.lambda$new$10(PokemonTab.java:249)
[16:10:51]: 	at me.corriekay.pokegoutil.windows.PokemonTab$$Lambda$106/30775581.stateChanged(Unknown Source)
[16:10:51]: 	at me.corriekay.pokegoutil.utils.helpers.LDocumentListener$1.lambda$changedUpdate$0(LDocumentListener.java:58)
[16:10:51]: 	at me.corriekay.pokegoutil.utils.helpers.LDocumentListener$1$$Lambda$108/9520332.run(Unknown Source)
[16:10:51]: 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
[16:10:51]: 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[16:10:51]: 	at java.awt.EventQueue.access$500(Unknown Source)
[16:10:51]: 	at java.awt.EventQueue$3.run(Unknown Source)
[16:10:51]: 	at java.awt.EventQueue$3.run(Unknown Source)
[16:10:51]: 	at java.security.AccessController.doPrivileged(Native Method)
[16:10:51]: 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
[16:10:51]: 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[16:10:51]: 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[16:10:51]: 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[16:10:51]: 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[16:10:51]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[16:10:51]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[16:10:51]: 	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Wolfsblvt** [comment]
Same as #541.
NullPointer cause of new moves that BPGM does not support currently.
