### ISSUE TITLE
I can no longer log in from around 2017/02/24 AM 9: 00(JST).

### ISSUE THREAD

**Issue by Sentaroh** [Wolfsblvt/BlossomsPokemonGoManager#550]
Unknown exception occurred. 
[09:22:19]: com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
[09:22:19]: 	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:53)
[09:22:19]: 	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:164)
[09:22:19]: 	at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:122)
[09:22:19]: 	at com.pokegoapi.api.PokemonGo.login(PokemonGo.java:193)
[09:22:19]: 	at me.corriekay.pokegoutil.data.managers.AccountController.logOn(AccountController.java:337)
[09:22:19]: 	at me.corriekay.pokegoutil.BlossomsPoGoManager.lambda$openOldGui$1(BlossomsPoGoManager.java:114)
[09:22:19]: 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
[09:22:19]: 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[09:22:19]: 	at java.awt.EventQueue.access$500(Unknown Source)
[09:22:19]: 	at java.awt.EventQueue$3.run(Unknown Source)
[09:22:19]: 	at java.awt.EventQueue$3.run(Unknown Source)
[09:22:19]: 	at java.security.AccessController.doPrivileged(Native Method)
[09:22:19]: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[09:22:19]: 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[09:22:19]: 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[09:22:19]: 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[09:22:19]: 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[09:22:19]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[09:22:19]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[09:22:19]: 	at java.awt.EventDispatchThread.run(Unknown Source)
[09:22:19]: Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
[09:22:19]: 	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
[09:22:19]: 	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
[09:22:19]: 	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
[09:22:19]: 	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:42)
[09:22:19]: 	... 19 more
[09:22:19]: Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
[09:22:19]: 	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:115)
[09:22:19]: 	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:92)
[09:22:19]: 	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
[09:22:19]: 	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
[09:22:19]: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
[09:22:19]: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[09:22:19]: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
[09:22:19]: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[09:22:19]: 	at rx.Observable.subscribe(Observable.java:9957)
[09:22:19]: 	at rx.Observable.subscribe(Observable.java:9924)
[09:22:19]: 	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
[09:22:19]: 	... 21 more
[09:22:19]: Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
[09:22:19]: 	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:82)
[09:22:19]: 	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:342)
[09:22:19]: 	at java.lang.Thread.run(Unknown Source)

**Comment by Wolfsblvt** [comment]
Already known. Niantic changed login routine for the legacy stuff without the hashkey service.
We are working on it.

**Comment by Sentaroh** [comment]
Thank you quick response.

**Comment by Wolfsblvt** [comment]
Fixed with #548.
