### ISSUE TITLE
Error at trainer/pokemon level 40

### ISSUE THREAD

**Issue by crystallinity** [Wolfsblvt/BlossomsPokemonGoManager#553]
as discussed in discord, after the gen2 release i get an error after the google auth login, with or without the hash key added to config.json:

```
[14:59:56]: Successfully logged in. Welcome, crystallinity33.
[14:59:56]: Hash Version: 0.57.02
[14:59:56]: Stats: Lvl 40 Mystic player.
[14:59:56]: Pokédex - Types Caught: 202, Total Pokémon Caught: 56038, Total Current Pokémon: 766 (+8 Eggs)
[14:59:56]: Current version: v0.1.7
[14:59:56]: Load saved locations from file.
[14:59:56]: java.lang.IndexOutOfBoundsException: Index: 40, Size: 40
[14:59:56]: 	at java.util.ArrayList.rangeCheck(Unknown Source)
[14:59:56]: 	at java.util.ArrayList.get(Unknown Source)
[14:59:56]: 	at java.util.Collections$UnmodifiableList.get(Unknown Source)
[14:59:56]: 	at POGOProtos.Settings.Master.PokemonUpgradeSettingsOuterClass$PokemonUpgradeSettings.getStardustCost(PokemonUpgradeSettingsOuterClass.java:236)
[14:59:56]: 	at com.pokegoapi.api.pokemon.PokemonCpUtils.getStartdustCostsForPowerup(PokemonCpUtils.java:189)
[14:59:56]: 	at com.pokegoapi.api.pokemon.PokemonDetails.getStardustCostsForPowerup(PokemonDetails.java:430)
[14:59:56]: 	at me.corriekay.pokegoutil.data.enums.PokeColumn$23.get(PokeColumn.java:204)
[14:59:56]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTableModel.lambda$updateTableData$0(PokemonTableModel.java:48)
[14:59:56]: 	at java.util.ArrayList.forEach(Unknown Source)
[14:59:56]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTableModel.updateTableData(PokemonTableModel.java:43)
[14:59:56]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTable.constructNewTableModel(PokemonTable.java:180)
[14:59:56]: 	at me.corriekay.pokegoutil.windows.PokemonTab.refreshList(PokemonTab.java:1046)
[14:59:56]: 	at me.corriekay.pokegoutil.windows.PokemonTab.lambda$new$10(PokemonTab.java:254)
[14:59:56]: 	at me.corriekay.pokegoutil.utils.helpers.LDocumentListener$1.lambda$changedUpdate$0(LDocumentListener.java:58)
[14:59:56]: 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
[14:59:56]: 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[14:59:56]: 	at java.awt.EventQueue.access$500(Unknown Source)
[14:59:56]: 	at java.awt.EventQueue$3.run(Unknown Source)
[14:59:56]: 	at java.awt.EventQueue$3.run(Unknown Source)
[14:59:56]: 	at java.security.AccessController.doPrivileged(Native Method)
[14:59:56]: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[14:59:56]: 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[14:59:56]: 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[14:59:56]: 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[14:59:56]: 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[14:59:56]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[14:59:56]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[14:59:56]: 	at java.awt.EventDispatchThread.run(Unknown Source)
[14:59:56]: Latest version from server: v0.1.7

```

**Comment by Wolfsblvt** [comment]
Issue with Pokémon level und Stardust cost retrieval it seems.

**Comment by Wolfsblvt** [comment]
Thanks for reporting this and for using BlossomsPokemonGoManager. This project is no longer maintained and no longer works with current Pokémon Go services, so I’m closing all remaining issues as part of archiving it. Please do not use it with a live account or current credentials. See the [Disclaimer](https://github.com/Wolfsblvt/BlossomsPokemonGoManager#disclaimer) for details.

**Comment by Wolfsblvt** [comment]
Thanks for reporting this and for using the project. Blossoms Pokémon Go Manager is no longer maintained and no longer works with current Pokémon Go services, so I’m closing all remaining issues as part of archiving the repository. This avoids leaving a false impression that further development or support is planned.
