### ISSUE TITLE
Browser doesn't launch for Google Auth code

### ISSUE THREAD

**Issue by hhu94** [Wolfsblvt/BlossomsPokemonGoManager#95]
I'm running on Arch Linux with Chromium as the default browser, but Firefox is installed too. None of them open a new tab for the auth code, running `java -jar BlossomsPogoManager.jar` doesn't output anything, it just terminates.

**Comment by hhu94** [comment]
```
[08/08 06:05:04]: Exception in thread "main" [08/08 06:05:04]: java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
[08/08 06:05:04]:   at java.awt.Desktop.checkActionSupport(Desktop.java:225)
[08/08 06:05:04]:   at java.awt.Desktop.browse(Desktop.java:381)
[08/08 06:05:04]:   at me.corriekay.pokegoutil.BlossomsPoGoManager.logOn(BlossomsPoGoManager.java:175)
[08/08 06:05:04]:   at me.corriekay.pokegoutil.BlossomsPoGoManager.main(BlossomsPoGoManager.java:50)
```

**Comment by Wolfsblvt** [comment]
Yeah, seems like the `Desktop.browse` is not available under your operating system. We will fix that.

For the time being, you can bookmark yourself the Token generation URL and use that:
[Google API token generation](https://accounts.google.com/o/oauth2/auth?client_id=848232511240-73ri3t7plvk96pj4f85uj8otdat2alem.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=openid%20email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email)

**Comment by hhu94** [comment]
@Wolfsblvt the application just terminates after I click OK on the browser launch popup. I have nowhere to input my token.

**Comment by Wolfsblvt** [comment]
Ay, too bad. Did it already create a config.json for you?
If not, try creating one in the folder where the jar file is with the following content:

```
{
    "login": {
        "GoogleAuthToken": "yourtokenhere",
        "SaveAuth": true
    }
}
```

If it's already there, just add the login login value, or overwrite the contents.
That should autologin you with that token.

**Comment by hhu94** [comment]
@Wolfsblvt It did create the json file for me. I input my token as you said and now I get "Unfortunately, your login has failed. Press OK to try again."

**Comment by Wolfsblvt** [comment]
You have made sure that the GoogleAuthToken is exactly like you copied it? No trailing spaces, etc.
My file looks like:

```
{
    "options": {"lang": "en"},
    "login": {
        "GoogleAuthToken": "1/bgp4xsdfggggS82w2axxaftgae9osvettetd6g",
        "SaveAuth": true
    }
}
```

Otherwise you have to be patient sadly and wait for a fix.

**Comment by hhu94** [comment]
Yes, I made absolutely sure it's the token's correctly copied.

**Comment by Wolfsblvt** [comment]
Currently working on a cross-platform fix. Guess you have to test it then though, I don't have a linux system that doesn't have the Gnome libraries :P

**Comment by hhu94** [comment]
Give me a jar and I'll test it :)

**Comment by lukezona** [comment]
Same problem here:

Windows 10 on Virtual Machine.
Manually set Google login in config.json as written above (of course I used my Auth Token)

When I launch the .jar and select Google login it doesn't work and says: 
"Unfortunately your login has failed. Press OK to try again".

And in Console file there's written:

> [08/08 16:00:40]: D/GoogleUserCredentialProvider: 0
> [08/08 16:02:44]: D/GoogleUserCredentialProvider: 0

I have to wait the fix or there's a way to make it works?

**Comment by Wolfsblvt** [comment]
Can one test this file please?
It should have enough fallback code and cross-platform-handling.

Just note that this is the latest dev version. It's maybe not stable, and should be just used to test if login works.

_EDIT: Removed file_

**Comment by hhu94** [comment]
Still doesn't work

```
[08/08 08:35:22]: Could not fetch config item 'login.PTCUsername'! Fallback to default: null
[08/08 08:35:22]: Could not fetch config item 'login.PTCPassword'! Fallback to default: null
[08/08 08:35:23]: Could not fetch config item 'login.GoogleAuthToken'! Fallback to default: null
[08/08 08:35:24]: Exception in thread "main" [08/08 08:35:24]: java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
[08/08 08:35:24]:   at java.awt.Desktop.checkActionSupport(Desktop.java:225)
[08/08 08:35:24]:   at java.awt.Desktop.browse(Desktop.java:381)
[08/08 08:35:24]:   at me.corriekay.pokegoutil.utils.Browser.openUrl(Browser.java:17)
[08/08 08:35:24]:   at me.corriekay.pokegoutil.controllers.AccountController.logOn(AccountController.java:122)
[08/08 08:35:24]:   at me.corriekay.pokegoutil.BlossomsPoGoManager.main(BlossomsPoGoManager.java:19)
```

**Comment by Wolfsblvt** [comment]
Okay, can you test it again?
I have fixed and added exception handling, but caught the wrong exception xD

_EDIT: Link removed_

**Comment by Wolfsblvt** [comment]
The PR got merged, we are still waiting for answer if it is actually fixed, then we'll close it here.

**Comment by hhu94** [comment]
It works now! Thank you very much :)
